### ISSUE TITLE
Legacy

### ISSUE THREAD

**Issue by rmartinez1980** [johnanthonyeletto/homebridge-windmill-ac#1]
**Is your feature request related to a problem? Please describe:**
I am using the legacy version of the app to control the AC over WiFi however the plugin suggest a token, which I am unable to obtain utilizing the method described within the README. 

**Describe the solution you'd like:**
The ability to configure legacy Units

**Comment by johnanthonyeletto** [comment]
Hi @rmartinez1980 thanks for the feature request. Are you able to login to dashboard.windmillair.com with the legacy version?

**Comment by rmartinez1980** [comment]
The legacy version doesn’t load to the dashboard unfortunately

**Comment by rmartinez1980** [comment]
It has a separate app to control the AC with your phone

**Comment by johnanthonyeletto** [comment]
@rmartinez1980 the new AC uses the Blynk IOT platform, and it looks according to [this issue](https://github.com/tuya/tuya-home-assistant/issues/352) that the legacy AC possibly used the Tuya platform. 

If you are able to confirm that your AC uses the Tuya platform, we might be able to add support in this plug-in. 

Otherwise, it might be worth trying the Tuya plug-in that the issue linked above belongs to.

**Comment by johnanthonyeletto** [comment]
Trying to add your AC in the [Tuya app](https://apps.apple.com/us/app/tuya-smart/id1034649547) might be a good way to start testing.

**Comment by rmartinez1980** [comment]
I believe you are correct, when I add it to google home it shows tuya then does a redirect to windmill AC. I attached screen shot 

![IMG_1966](https://github.com/johnanthonyeletto/homebridge-windmill-ac/assets/68136485/533fe8de-5944-44c9-b14c-3aff77e4781b)

**Comment by johnanthonyeletto** [comment]
Got it. It looks like there's an [official Tuya Homebridge plug-in](https://github.com/tuya/tuya-homebridge) it might be worth trying that, and it's nice that it has official support.

**Comment by rmartinez1980** [comment]
That brings a whole new set of issues. Mainly on the tuya Developer portal. You can add the AC to the Tuya or Smartlife app but getting to load as one of the devices on the developer portal hasn't worked

**Comment by johnanthonyeletto** [comment]
Oh man. There probably won't be much you can do without an API key whether you use this plug-in or another one.
