### ISSUE TITLE
Windmill A/C auth token not listed in online dashboard

### ISSUE THREAD

**Issue by clifg** [johnanthonyeletto/homebridge-windmill-ac#8]
**Describe Your Problem:**

We have the last-gen Windmill A/C (now called the "Classic" I believe, not the Whispertech) and the dashboard.windmillair.com site no longer has the auth token shown for A/C units. Are there any other ways to find this token?

**Screenshots:**

<img width="613" alt="Screenshot 2024-05-05 at 4 39 00 PM" src="https://github.com/johnanthonyeletto/homebridge-windmill-ac/assets/8487034/8455b007-e311-4f76-b73a-fe31f923beb8">

**Comment by beret** [comment]
I had the same issue. The token is there in the source code for the webpage. Navigate to the specific AC unit you want, then open the info ℹ️ panel, then view source.

The key is a 32 character mixed upper/lowercase alphanumeric string which may have special characters.

Easiest way is to search the page source code for the name of your AC. (eg. Living Room)

The API key should be right after one of the results. In my case, it was the element after the second result. (Below)

PS: Be sure to make a note of these somewhere safe so you don’t have to rely on the website for it.

```
<td class="ant-table-cell ant-table-column-sort ant-table-cell-fix-left ant-table-cell-fix-left-last ant-table-cell-ellipsis" style="position: sticky; left: 64px;"><span class="ant-table-cell-content"><div class="ant-table-first-column ant-table-clickable-column" style="cursor: pointer; min-height: 20px; min-width: 150px; font-weight: 600; text-overflow: ellipsis; overflow: hidden;">NAME OF YOUR AC</div></span></td>
<td class="ant-table-cell ant-table-cell-ellipsis">KEYISHERE</td>
```

selector path: `#search-table > div > div.ant-table-body > div > table > tbody > tr:nth-child(3) > td:nth-child(3)`

**Comment by nathancoleman** [comment]
@beret are you still able to find your token in the page source? It's looking to me like they might have removed that as well 😢 

Edit: I was able to find the token by digging into the websocket messages using Chrome dev tools

**Comment by sleepdefic1t** [comment]
You can also find your token by using the app (in my case, iOS) to send logs to yourself.

---

`👤(user menu, top left) > About > Send Logs`

A new email modal will pop up which contains your log files.

Change `To:` to your email address,  
delete the `Cc:` address, and  
send it to yourself.

Search any of these log files for "token".

---

Hope this helps ✊

<br/>

note: the token will change any time you have to reconfigure your network connection. A pain in my case because I'm having the issue where the unit's settings change randomly and disconnects from wifi.

**Comment by ggilbert899** [comment]
Hi There....For some reason when I try to enable logging by following the instructions above I get the following error:  Logging Turned Off.  You can turn on logging in Windmill Air Settings section in Settings App.  For some reason I can't find where to enable logging

**Comment by clifg** [comment]
> You can also find your token by using the app (in my case, iOS) to send logs to yourself.
> 
> `👤(user menu, top left) > About > Send Logs`
> 
> A new email modal will pop up which contains your log files.
> 
> Change `To:` to your email address, delete the `Cc:` address, and send it to yourself.
> 
> Search any of these log files for "token".
> 
> Hope this helps ✊
> 
> 
> note: the token will change any time you have to reconfigure your network connection. A pain in my case because I'm having the issue where the unit's settings change randomly and disconnects from wifi.

Thank you! Finally got a chance to try this out today and it worked like a charm.

**Comment by clifg** [comment]
I'm going to close the issue since there's a workaround and to keep the issues list clean
